sudo: false
language: node_js

node_js:
  - 12

branches:
  only:
    - main
    - posts

before_install:
  - npm install -g hexo-cli
  - npm install hexo-posts-sync --save

install:
  - npm install

script:
  - hexo generate

after_script:
  - git config user.name "hqwhqwhq"
  - git config user.email "hqwhqwhq@163.com"
  - sed -i "s/blog_token/${blog_token}/g" ./_config.yml
  - hexo deploy