sudo: false
language: node_js

node_js:
  - 12

cache:
  npm: true

branches:
  only:
    - main

before_install:
  - npm install -g hexo-cli

install:
  - npm install

script:
  - hexo clean

after_script:
  - git config user.name "hqwhqwhq"
  - git config user.email "hqwhqwhq@163.com"
  - sed -i "s/blog_token/${blog_token}/g" ./_config.yml
  - hexo g -d